### ISSUE TITLE
Error preparing a build tree - Lua Bindings

### ISSUE THREAD

**Issue by ThibFrgsGmz** [jphickey/cfe-eds-framework#6]
**Describe the bug**

At least in my environment, the build tree preparation step is not error-free.

Before proceeding, I installed the dependencies listed in the [README.md](https://github.com/jphickey/cfe-eds-framework#prerequisites) file:

``sudo apt-get install build-essential cmake libexpat1-dev liblua5.3-dev libjson-c-dev python3-dev``

Despite this, when I run the make command ``make SIMULATION=native prep``, I get the following CMake errors:

```
ThibFrgsGmz@ThibFrgsGmz:/mnt/c/Users/CODES/cfe-eds-framework$ make SIMULATION=native prep
mkdir -p "build"
(cd "build/" && cmake  -DCMAKE_INSTALL_PREFIX=/exe -DCMAKE_BUILD_TYPE=debug "/mnt/c/Users/FARGES/Documents/VS_Code/cfe-eds-framework/cfe")
-- OMIT_DEPRECATED=false: Deprecated elements included in build
-- Search path for modules: apps;libs;psp/fsw/modules;cfe/modules
-- Module 'ci_lab' found at /mnt/c/Users/CODES/cfe-eds-framework/apps/ci_lab
-- Module 'to_lab' found at /mnt/c/Users/CODES/cfe-eds-framework/apps/to_lab
-- Module 'sch_lab' found at /mnt/c/Users/CODES/cfe-eds-framework/apps/sch_lab
-- Module 'sample_app' found at /mnt/c/Users/CODES/cfe-eds-framework/apps/sample_app
-- Module 'sample_lib' found at /mnt/c/Users/CODES/cfe-eds-framework/apps/sample_lib
-- Module 'edslib' found at /mnt/c/Users/CODES/cfe-eds-framework/tools/eds/edslib
-- Module 'missionlib' found at /mnt/c/Users/CODES/cfe-eds-framework/tools/eds/cfecfs/missionlib
-- Module 'cfe-core' found at /mnt/c/Users/CODES/cfe-eds-framework/cfe/fsw/cfe-core
-- Module 'osal' found at /mnt/c/Users/CODES/cfe-eds-framework/osal
-- Module 'psp' found at /mnt/c/Users/CODES/cfe-eds-framework/psp
-- Generated cfe_mission_cfg.h from /mnt/c/Users/CODES/cfe-eds-framework/sample_defs configuration
-- Generated cfe_perfids.h from /mnt/c/Users/CODES/cfe-eds-framework/sample_defs configuration
-- Setting up EDS toolchain build...
-- Checking for one of the modules 'lua-5.3;lua5.3;lua-5.2;lua5.2;lua-5.1;lua5.1;lua>=5.1'
    Lua support not configured, skipping EdsLib Lua bindings
-- Checking for one of the modules 'json-c;json'
    JSON support not configured, skipping EdsLib JSON bindings
-- Checking for one of the modules 'python3>=3.4'
    Python support not configured, skipping EdsLib Python bindings
CMake Error at /mnt/c/Users/CODES/cfe-eds-framework/tools/eds/tool/CMakeLists.txt:50 (message):
  Lua bindings are required to execute the EDS tool - install the Lua
  development packages


-- Configuring incomplete, errors occurred!
See also "/mnt/c/Users/CODES/cfe-eds-framework/build/CMakeFiles/CMakeOutput.log".
make: *** [Makefile:127: prep] Error 1
```

**To Reproduce**
Steps for replicating the behavior:
1. Install prerequisites ``sudo apt-get install build-essential cmake libexpat1-dev liblua5.3-dev libjson-c-dev python3-dev``
2. Prepare a build tree ``make SIMULATION=native prep``
3. See error ``Lua bindings are required to execute the EDS tool - install the Lua development packages``.

**Expected behavior**
The generation of the build tree is error-free.

**Code snips**
N/A

**System observed on:**
 - Hardware: Laptop
 - OS: WSL-2 Ubuntu 20.04
 - Versions project's last commit ``e70cb1b2``

**Additional context**
I'm not sure if it's because of the use of WSL-2, but I believe the project is missing a dependency.

**Reporter Info**
N/A

**Comment by ThibFrgsGmz** [comment]
If I install Lua from its sources (https://www.lua.org/download.html):

```sh
curl -R -O http://www.lua.org/ftp/lua-5.4.3.tar.gz
tar zxf lua-5.4.3.tar.gz
cd lua-5.4.3
make all test
```

The generation chain progresses past the point at which the error occurred:

```sh
-- PSP Selection: pc-linux
-- Building Core Module: edslib
    Lua support not configured, skipping EdsLib Lua bindings
    JSON support not configured, skipping EdsLib JSON bindings
    Python support not configured, skipping EdsLib Python bindings
-- Building Core Module: missionlib
```

I thought this solved the problem for the entire project, but when I run the ``make all`` command, I get the following error:

```sh
[ 87%] Built target sedstool
Scanning dependencies of target edstool-execute
make[4]: Warning: File 'eds/tool/sedstool' has modification time 0.0067 s in the future
[ 89%] Generating edstool-complete.stamp
/mnt/c/Users/CODES/cfe-eds-framework/tools/eds/tool/src/seds_outputfile.c:554:fatal: /mnt/c/Users/CODES/cfe-eds-framework/build - No such file or directory
Aborted
make[4]: *** [CMakeFiles/edstool-execute.dir/build.make:93: edstool-complete.stamp] Error 134
make[3]: *** [CMakeFiles/Makefile2:555: CMakeFiles/edstool-execute.dir/all] Error 2
make[2]: *** [CMakeFiles/Makefile2:508: CMakeFiles/mission-all.dir/rule] Error 2
make[1]: *** [Makefile:253: mission-all] Error 2
make: *** [Makefile:120: all] Error 2

```

I'm not sure if the issue is a flaw in the first step.

**Comment by jphickey** [comment]
Disclaimer - none of this has been tested on WSL... 

The dependency locating is done via the CMake "pkgconfig" module, which relies on the underlying pkg-config being set up correctly, which should be part of the build-essential but perhaps its not.

For example you should be able to run the following on the command line, to check for the compiler flags to use when building with Lua:
```
$ pkg-config --cflags lua5.3
-I/usr/include/lua5.3
```

This is from a native Ubuntu install, if WSL build environment works it should return similarly.  CMake is basically doing the same thing to determine the Lua include path.  It is evident from your initial trace that this did not work.

**Comment by ThibFrgsGmz** [comment]
I was successful in getting your project to work; the second error I mentioned was the presence of a white-space in the name of a folder (set by default in the French version of Windows). I am able to run all of the other commands once the white-space has been removed.

Because I don't know how the buildchain was repaired, I used Docker to create an Ubuntu 20.04 image (https://hub.docker.com/ /ubuntu) to start with a clean environment.
I executed the following command sequence:

```apt-get install git make cmake build-essential libexpat1-dev liblua5.3-dev libjson-c-dev python3-dev```

I was able to complete the build chain using this alone, but this is not a WSL-2 configuration.

Perhaps we can improve the prerequisites section by running apt-get install?

For WSL-2, I need to empty it of all the packages I've installed over time.
According to what I understand, the recommended method for installing Lua is via curl, so I assume that installing Lua via this method afterward has updated a path required by the build chain.

During the day, I'll try uninstalling and reinstalling my WSL-2 to see what solved the problem.
If I don't have time to go over it again and other people have the same issue, I'll recommend installing Lua via curl.

**Comment by ThibFrgsGmz** [comment]
As an aside, I ran the command you provided and got the same result.

**Comment by ThibFrgsGmz** [comment]
Well, I reinstalled the most recent version of WSL:

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

And I had the same issue as the original problem, but as an expat:

```
CMake Error at /mnt/c/Users/CODES/cfe-eds-framework/tools/eds/tool/CMakeLists.txt:42 (message):
  The Expat library is required for the build - install the expat development
  packages
```

Then, after a few commands, it worked:

1. ``make all`` failed and produced the same result for the expat development package.
2. ``sudo make SIMULATION=native prep`` with access permission: but ran into the same problem.
3. ``lsb_release -a`` to print the operating system configuration shown above.
4. ``sudo make SIMULATION=native prep`` which is the same as the second command, and the command was successful...

Based on my commands, I believe the issue would be caused by WSL instability.

I'm hoping that this will help others who are in the same situation as me.
